### PR TITLE
Update README and use it for PyPI package home page

### PR DESCRIPTION
**Pull request by mckayward**
I updated the README to reference more up-to-date documentation. I also changed it to the `.rst` format, so that we can use it as the `long_description` field in `setup.py`. That way the package home page on PyPI will have the README info on it. GitHub doesn't have a problem parsing the `.rst` format, as you can see on [my branch](https://github.com/mckayward/floyd-cli/tree/feature/update_readme).

I also uploaded this code onto testpypi.python.org to make sure that parsing of the README works. You can see it [here](https://testpypi.python.org/pypi?:action=display&name=mckay-floyd-cli&version=0.9.2).

@narenst, if you want to stick with `.md` format, I can just revert my last commit. Also, let me know your thoughts on the new format. Maybe we should add a link to the GitHub repo?

### CODE REVIEW

**Comment by narenst** [comment]
Thanks for this. I like that we can add useful README to pypi as well. I like the format you have here. It would be great if we can a couple of more things:

- Info on how to install floyd (just the simple installation case).
- One step showing how to create an account on floydhub and login from the cli.

Thanks!

**Comment by mckayward** [comment]
Sounds good. I'll make some updates on Monday.

**Comment by mckayward** [comment]
Okay I added some more sections to include what you mentioned. Man, `.rst` markdown is hard haha. I fiddled with this for quite a while. I think it's working and is being parsed into PyPI correctly too. I can make more edits if you'd like. Just let me know.

**Comment by narenst** [comment]
Looks great! Thanks for making the edits.

**Pull request merged**
