### PR TITLE
Caught requests.exceptions.Timeout exception class

### PR DESCRIPTION
**Pull request by msoedov**
#153

### CODE REVIEW

**Comment by houqp** [comment]
Timeout can be caused by load issue from FloydHub's servers too, which can be worked around with a retry. So I think it deserves a slightly different error message. Perhaps something like "Connection to FloydHub server timed out. Please retry or check your internet connection."

**Comment by houqp** [comment]
@msoedov sorry if my previous comment confused you. `requests.exceptions.ConnectionError` is still a unrecoverable error so retry won't help. For example, you will get this error when internet connection is down on the client side. So we need to handle those two exceptions in differently.

**Comment by msoedov** [comment]
@houqp I misread your first comment, fixed now

**Comment by houqp** [comment]
Thanks for the patch!

**Pull request merged**
